---
- name: simple is-is config
  gather_facts: False
  hosts: routers
  tasks:

    - name: generate is-is config 
      template:
        src: "./templates/is-is.j2"
        dest: ./
      loop: "{{ interfaces }}"
      